import smtplib
import os
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

class Notifier:
    def __init__(self):
        self.email_user = os.getenv('EMAIL_USER')
        self.email_pass = os.getenv('EMAIL_PASSWORD')
        
        if not self.email_user or not self.email_pass:
            raise ValueError("Email credentials missing from .env file.")

    def send_report(self, report_body):
        print("   [+] Formatting and sending email...")
        
        msg = MIMEMultipart('alternative')
        msg['From'] = "Market Agent <" + self.email_user + ">"
        msg['To'] = self.email_user
        msg['Subject'] = f"Daily Intelligence Briefing"

        # 1. Convert the AI's Markdown text to HTML
        # We use 'fenced_code' so if the AI sends a table/code block, it renders correctly
        html_content = markdown.markdown(report_body, extensions=['fenced_code', 'tables'])

        # 2. Wrap it in a Professional Financial Template (CSS)
        styled_html = f"""
        <html>
          <head>
            <style>
              body {{
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                color: #333333;
                line-height: 1.6;
                background-color: #f4f4f4;
                margin: 0;
                padding: 20px;
              }}
              .container {{
                max-width: 650px;
                margin: 0 auto;
                background-color: #ffffff;
                padding: 40px;
                border-radius: 8px;
                box-shadow: 0 2px 5px rgba(0,0,0,0.1);
              }}
              h1 {{
                color: #003366; /* Financial Navy Blue */
                border-bottom: 2px solid #003366;
                padding-bottom: 10px;
                font-size: 24px;
                margin-top: 0;
              }}
              h2, h3 {{
                color: #003366;
                margin-top: 25px;
                font-size: 18px;
                text-transform: uppercase;
                letter-spacing: 1px;
              }}
              p {{
                margin-bottom: 15px;
              }}
              strong {{
                color: #d35400; /* Subtle Orange for Emphasis */
              }}
              ul {{
                padding-left: 20px;
                margin-bottom: 20px;
              }}
              li {{
                margin-bottom: 8px;
              }}
              /* This makes your Portfolio/Data tables look like code blocks */
              pre {{
                background-color: #f8f9fa;
                border-left: 4px solid #003366;
                padding: 15px;
                font-family: 'Consolas', 'Monaco', monospace;
                font-size: 13px;
                white-space: pre-wrap; /* Wraps text on mobile */
                overflow-x: auto;
              }}
              .footer {{
                margin-top: 30px;
                font-size: 12px;
                color: #888;
                text-align: center;
                border-top: 1px solid #eee;
                padding-top: 20px;
              }}
            </style>
          </head>
          <body>
            <div class="container">
              {html_content}
              <div class="footer">
                Generated by Gemini 2.5 • Hostinger VPS • Automated Daily Brief
              </div>
            </div>
          </body>
        </html>
        """

        # Attach both Plain Text (backup) and HTML (primary)
        part1 = MIMEText(report_body, 'plain')
        part2 = MIMEText(styled_html, 'html')

        msg.attach(part1)
        msg.attach(part2)

        try:
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(self.email_user, self.email_pass)
            server.sendmail(self.email_user, self.email_user, msg.as_string())
            server.quit()
            print("   [+] Email sent successfully.")
        except Exception as e:
            print(f"   [!] Failed to send email: {e}")

if __name__ == "__main__":
    # Test with some dummy markdown to see the formatting
    dummy_text = "# Daily Report\n\n## Market Update\nThe market is **bullish** today.\n\n```\nAAPL: $150 (+2%)\nTSLA: $200 (-1%)\n```"
    notifier = Notifier()
    notifier.send_report(dummy_text)
